# Generated by Django 4.2.4 on 2023-08-29 23:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usipav', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registroacesso',
            old_name='Pagina',
            new_name='pagina',
        ),
        migrations.RemoveField(
            model_name='registroacesso',
            name='date',
        ),
        migrations.AddField(
            model_name='registroacesso',
            name='data_acesso',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
